
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_app_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'narwhal_orders_app_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] || ENV['DATABASE_NAME'] || 'narwhal_orders_app_production' %>

